name: CI Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout riseclipse-metamodel-nsd2016
      uses: actions/checkout@v2
      with:
        path: riseclipse-metamodel-nsd2016
        repository: RiseClipse/riseclipse-metamodel-nsd2016
        ref: dev-ci

    - name: Checkout riseclipse-validator-scl2003
      uses: actions/checkout@v2
      with:
        path: riseclipse-validator-scl2003
        repository: RiseClipse/riseclipse-validator-scl2003
        ref: dev-ci

    - name: Checkout riseclipse-validator-ocl
      uses: actions/checkout@v2
      with:
        path: riseclipse-validator-ocl
        repository: RiseClipse/riseclipse-validator-ocl
        ref: dev-ci

    - name: Checkout riseclipse-metamodel-scl2003
      uses: actions/checkout@v2
      with:
        path: riseclipse-metamodel-scl2003
        repository: RiseClipse/riseclipse-metamodel-scl2003
        ref: dev-ci

    - name: Checkout riseclipse-editor
      uses: actions/checkout@v2
      with:
        path: riseclipse-editor
        repository: RiseClipse/riseclipse-editor
        ref: Use-up-to-date-components

    - name: Checkout riseclipse-main
      uses: actions/checkout@v2
      with:
        path: riseclipse-main
        repository: RiseClipse/riseclipse-main
        ref: use-up-to-date-components

    - name: Checkout riseclipse-developer
      uses: actions/checkout@v2
      with:
        path: riseclipse-developer
        ref: dev-ci

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    # - name: Clean
    #   run: mvn clean package

    - name: Build with Maven 
      run: |
        cd riseclipse-developer
        cd fr.centralesupelec.edf.riseclipse.developer.maven.validator.scl
        mvn install

    - name: Run tests 
      run: |
        mv ${{ github.workspace }}/riseclipse-validator-scl2003/fr.centralesupelec.edf.riseclipse.iec61850.scl.validator/target/RiseClipseValidatorSCL-*.jar ${{ github.workspace }}/RiseClipse-Validator-SCL-CLI.jar
        mv ${{ github.workspace }}/riseclipse-validator-scl2003/fr.centralesupelec.edf.riseclipse.iec61850.scl.validator.ui/target/RiseClipseValidatorSCLApplication-*.jar ${{ github.workspace }}/RiseClipse-Validator-SCL-UI.jar
        mv ${{ github.workspace }}/riseclipse-validator-ocl/fr.centralesupelec.edf.riseclipse.validation.ocl/target/fr.centralesupelec.edf.riseclipse.validation.ocl-*.jar ${{ github.workspace }}/RiseClipse-Validator-OCL-CLI.jar
        mv ${{ github.workspace }}/riseclipse-metamodel-nsd2016/fr.centralesupelec.edf.riseclipse.iec61850.nsd/target/fr.centralesupelec.edf.riseclipse.iec61850.nsd-*.jar ${{ github.workspace }}/RiseClipse-Validator-NSD-CLI.jar

    - name: Upload artifact Validator SCL CLI
      uses: actions/upload-artifact@v2
      with:
        name: RiseClipse-Validator-SCL-CLI.jar
        path: ${{ github.workspace }}/RiseClipse-Validator-SCL-CLI.jar

    - name: Upload artifact Validator SCL UI
      uses: actions/upload-artifact@v2
      with:
        name: RiseClipse-Validator-SCL-UI.jar
        path: ${{ github.workspace }}/RiseClipse-Validator-SCL-UI.jar

    - name: Upload artifact Validator OCL CLI
      uses: actions/upload-artifact@v2
      with:
        name: RiseClipse-Validator-OCL-CLI.jar
        path: ${{ github.workspace }}/RiseClipse-Validator-OCL-CLI.jar

    - name: Upload artifact Validator NSD CLI
      uses: actions/upload-artifact@v2
      with:
        name: RiseClipse-Validator-NSD-CLI.jar
        path: ${{ github.workspace }}/RiseClipse-Validator-NSD-CLI.jar

  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps: 
    - name: Checkout riseclipse-validator-scl2003
      uses: actions/checkout@v2
      with:
        path: riseclipse-validator-scl2003
        repository: RiseClipse/riseclipse-validator-scl2003
        ref: test-scripts

    - name: Download artifact .jar
      uses: actions/download-artifact@master
      with:
        name: RiseClipse-Validator-SCL-CLI.jar
        path: ${{ github.workspace }}

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Run tests 
      run: |
        cd riseclipse-validator-scl2003/test   
        echo ${{ github.workspace }}
        ls ${{ github.workspace }}
        ./run_tests.sh ${{ github.workspace }}/RiseClipse-Validator-SCL-CLI.jar
