name: Build and test

# This CI workflow is trigger automatically for EVERY COMMIT or whenever a PULL REQUEST is REOPENED (open is already triggered by push)
# On PR creation, we only execute build and run tests since we don't want to release yet
# On master, the build artifacts will be used for releases 

on: 
  push: # Triggered every time on push except on master
    branches-ignore:
      - master
      - main 
  pull_request: # Trigger on PR
    types: [opened, reopened] 
  workflow_run:  # Trigger when requested manually from Release-Manual Workflow
    workflows: [Release manual]
    types:
      - completed
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      project_version: ${{ steps.get_version.outputs.project_version }}

    steps: 
    - name: Checkout riseclipse-metamodel-nsd2016
      uses: actions/checkout@v2
      with:
        path: riseclipse-metamodel-nsd2016
        repository: RiseClipse/riseclipse-metamodel-nsd2016
        ref: master

    - name: Checkout riseclipse-validator-scl2003
      uses: actions/checkout@v2
      with:
        path: riseclipse-validator-scl2003
        repository: RiseClipse/riseclipse-validator-scl2003
        ref: dev-ci

    - name: Checkout riseclipse-validator-ocl
      uses: actions/checkout@v2
      with:
        path: riseclipse-validator-ocl
        repository: RiseClipse/riseclipse-validator-ocl
        ref: master

    - name: Checkout riseclipse-metamodel-scl2003
      uses: actions/checkout@v2
      with:
        path: riseclipse-metamodel-scl2003
        repository: RiseClipse/riseclipse-metamodel-scl2003
        ref: master

    - name: Checkout riseclipse-editor
      uses: actions/checkout@v2
      with:
        path: riseclipse-editor
        repository: RiseClipse/riseclipse-editor
        ref: master

    - name: Checkout riseclipse-main
      uses: actions/checkout@v2
      with:
        path: riseclipse-main
        repository: RiseClipse/riseclipse-main
        ref: master

    - name: Checkout riseclipse-developer
      uses: actions/checkout@v2
      with:
        path: riseclipse-developer
        ref: ${{ github.ref_name }}

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven 
      run: |
        cd riseclipse-developer
        cd fr.centralesupelec.edf.riseclipse.developer.maven.validator.scl
        mvn install

    - name: Extract Maven project version
      run: |
        cd riseclipse-developer
        echo ::set-output name=project_version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: get_version

    - name: Show extracted Maven project version
      run: echo ${{ steps.get_version.outputs.project_version }}

    - name: Rename and move artifacts
      run: |
        mv ${{ github.workspace }}/riseclipse-validator-scl2003/fr.centralesupelec.edf.riseclipse.iec61850.scl.validator/target/RiseClipseValidatorSCL-${{ steps.get_version.outputs.project_version }}.jar ${{ github.workspace }}
        mv ${{ github.workspace }}/riseclipse-validator-scl2003/fr.centralesupelec.edf.riseclipse.iec61850.scl.validator.ui/target/RiseClipseValidatorSCLApplication-${{ steps.get_version.outputs.project_version }}.jar ${{ github.workspace }}

    - name: Upload artifact Validator SCL CLI
      uses: actions/upload-artifact@v2
      with:
        name: RiseClipseValidatorSCL-${{ steps.get_version.outputs.project_version }}.jar
        path: ${{ github.workspace }}/RiseClipseValidatorSCL-${{ steps.get_version.outputs.project_version }}.jar

    - name: Upload artifact Validator SCL UI
      uses: actions/upload-artifact@v2
      with:
        name: RiseClipseValidatorSCLApplication-${{ steps.get_version.outputs.project_version }}.jar
        path: ${{ github.workspace }}/RiseClipseValidatorSCLApplication-${{ steps.get_version.outputs.project_version }}.jar

  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps: 
    - name: Checkout riseclipse-validator-scl2003-test
      uses: actions/checkout@v2
      with:
        path: riseclipse-validator-scl2003-test
        repository: RiseClipse/riseclipse-validator-scl2003-test
        ref: master

    - name: Checkout riseclipse-validator-scl2003
      uses: actions/checkout@v2
      with:
        path: riseclipse-validator-scl2003
        repository: RiseClipse/riseclipse-validator-scl2003
        ref: master

    - name: Download artifact .jar
      uses: actions/download-artifact@master
      with:
        name: RiseClipseValidatorSCL-${{ needs.build.outputs.project_version }}.jar
        path: ${{ github.workspace }}

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Run tests  
      run: | 
        cd riseclipse-validator-scl2003-test    
        echo ${{ github.workspace }} 
        ls ${{ github.workspace }} 
        ./scripts/run_tests.sh -o -n -j ${{ github.workspace }}/RiseClipseValidatorSCL-${{ needs.build.outputs.project_version }}.jar
