name: Build and test

# This CI workflow is trigger automatically for EVERY COMMIT or whenever a PULL REQUEST is REOPENED (open is already triggered by push)
# On PR creation, we only execute build and run tests since we don't want to release yet
# On master, the build artifacts will be used for releases 

on: 
  push: # Triggered every time on push
  pull_request: # Trigger on PR (already triggered by push when oppened)
    types: [reopened] 

jobs:
  name: Build / Test
  call-build-test-workflow:
    uses: riseclipse/riseclipse-workflows/.github/workflows/Build-Test.yml@master
    with:
      buildPath: fr.centralesupelec.edf.riseclipse.developer.maven.validator.scl
