name: Rollback Failure

# If for some reason one of the release workflows failed, rollback and delete release branch

on: workflow_call

jobs:
  on-failure:
    runs-on: ubuntu-latest

    steps:
    # Get artefacts and version
      - name: Checkout riseclipse-developer
        uses: actions/checkout@v2
        with:
          path: riseclipse-developer
          ref: ${{ github.ref_name }}

      - name: Extract Maven project version
        run: |
          cd riseclipse-developer
          echo ::set-output name=project_version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: get_version

      - name: delete branch if created
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: release/v${{ steps.get_version.outputs.project_version }}

# What to do next ??