name: Release on OSSRH and Maven Central

# This CD workflow releases packages to OSSRH Nexus repository and to Maven Central
# It only runs on MASTER branch AFTER Build and Test Workflow is completed AND if commit is tagged (which is done when merging)
# NOTE: Maven central needs aproval in Nexus OSSRH before being released

on:
  workflow_run:
    workflows: [Build and test]
    types:
      - completed
    branches: [master, main]

jobs:
  publish_release:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout riseclipse-developer
      uses: actions/checkout@v2
      with:
        path: riseclipse-developer
        repository: RiseClipse/riseclipse-developer
        ref: master

    - name: release_ossrh_central
      run: |
        cd riseclipse-developer/fr.centralesupelec.edf.riseclipse.developer.maven.validator.scl
        # mvn release:perform
