# This CD workflow releases packages to Docker Hub
# It only runs on MASTER branch AFTER Build and Test Workflow is completed AND if commit is tagged (which is done when merging previous commits)

name: Release DockerHub

on:
  workflow_run:
    workflows: [Build and test]
    types:
      - completed
    branches: [master, main]

jobs:
  publish_dockerhub:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && contains(github.ref, 'refs/tags/')

    steps: 
    # Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: alsoares59/riseclipse

    # Get Dockerfiles from checkout
    - name: Checkout riseclipse-validator-scl2003
      uses: actions/checkout@v2
      with:
        path: riseclipse-validator-scl2003
        repository: RiseClipse/riseclipse-validator-scl2003
        ref: ${{ github.ref_name }}

    # Download and unzip artefacts
    - name: Download artifact zip
      uses: actions/download-artifact@master
      with:
        name: RiseClipse.zip
        path: ${{ github.workspace }}

    - name: Unzip artefacts
      run: |
        unzip RiseClipse.zip -d ${{ github.workspace }}

    # Build and push images for each validator
    - name: Build and push Docker image Validator SCL CLI
      uses: docker/build-push-action@v2
      with:
        context: ${{ github.workspace }}
        file: ${{ github.workspace }}/riseclipse-validator-scl2003/Dockerfile
        push: true
        tags: alsoares59/riseclipse:validator-scl-${{ needs.build.outputs.project_version }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: GH_WS=${{ github.workspace }}
