name: Release manual

on: workflow_dispatch  # Manual trigger only for master/main

jobs:
  call-build-test-workflow:
    uses: riseclipse/riseclipse-workflows/.github/workflows/Build-Test.yml@master
    with:
      build-path: fr.centralesupelec.edf.riseclipse.editor
  call-release-github-workflow:
    uses: riseclipse/riseclipse-workflows/.github/workflows/Release-GitHub.yml@master
  call-release-maven-workflow:
    uses: riseclipse/riseclipse-workflows/.github/workflows/Release-Maven.yml@master