name: Rollback Failure

# If for some reason one of the release workflows failed, rollback and delete release branch

on:
  workflow_run:
    workflows: [Release DockerHub, Release on GitHub IO site, Release on GitHub, Release on OSSRH and Maven Central]
    types:
      - completed
    branches: [master, main]

jobs:
  on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    call-failure-workflow:
    name: Rollback due to failure
    uses: riseclipse/riseclipse-workflows/.github/workflows/Release-Failure-Rollback.yml@master