name: Release manual

on: workflow_dispatch  # Manual trigger only for master/main

jobs:
  nothing:
    runs-on: ubuntu-latest

    steps: 
    - name: Does nothing
      run: echo "This workflow is only used to trigger the Build and Test workflow that will also trigger the releases if it is on main branch"