name: Run Tests

on:
  workflow_run:
    workflows: ["Build"]
    types: 
      - completed

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps: 
    - name: Download artifact .jar
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success
        path: ${{ github.workspace }}

    - name: Checkout riseclipse-metamodel-nsd2016
      uses: actions/checkout@v2
      with:
        path: riseclipse-metamodel-nsd2016
        repository: RiseClipse/riseclipse-metamodel-nsd2016
        ref: use-up-to-date-components

    - name: Checkout riseclipse-validator-scl2003
      uses: actions/checkout@v2
      with:
        path: riseclipse-validator-scl2003
        repository: RiseClipse/riseclipse-validator-scl2003
        ref: Use-up-to-date-components

    - name: Checkout riseclipse-validator-ocl
      uses: actions/checkout@v2
      with:
        path: riseclipse-validator-ocl
        repository: RiseClipse/riseclipse-validator-ocl
        ref: Use-up-to-date-components

    - name: Checkout riseclipse-metamodel-scl2003
      uses: actions/checkout@v2
      with:
        path: riseclipse-metamodel-scl2003
        repository: RiseClipse/riseclipse-metamodel-scl2003
        ref: use-up-to-date-components

    - name: Checkout riseclipse-editor
      uses: actions/checkout@v2
      with:
        path: riseclipse-editor
        repository: RiseClipse/riseclipse-editor
        ref: Use-up-to-date-components

    - name: Checkout riseclipse-main
      uses: actions/checkout@v2
      with:
        path: riseclipse-main
        repository: RiseClipse/riseclipse-main
        ref: use-up-to-date-components

    - name: Checkout riseclipse-developer
      uses: actions/checkout@v2
      with:
        path: riseclipse-developer
        ref: dev-ci

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    